### ISSUE TITLE
Add "translate" to "..." menu on posts and comments

### ISSUE THREAD

**Issue by mykdavies** [liftoff-app/liftoff#102]
Perhaps only where specified language is different from user defaults. Assuming people are actually using those fields correctly.
DeepL would be a nice candidate service to use.

**Comment by domage** [comment]
Finding a reliable free translation service can be challenging these days. A solution to consider could be similar to the approach adopted in Apollo.

When a user clicks on the "Translate" button in Apollo, it launches an internal web-browser view that directs to Google Translate. The user then inputs their Google Translate credentials, allowing the translation to occur within their own account.
The user's credentials are stored internally to avoid the necessity of logging in each time. 

Following this, the text to be translated is sent to Google Translate through a request (possibly a GET request?).

![Capture](https://github.com/liftoff-app/liftoff/assets/1536126/d7b9d88b-90bf-4307-b9f4-cbf99b193a54)

**Comment by mykdavies** [comment]
That's got to be way more scalable.

I just tested it out (while Apollo is still there) and it also works if you don't log into Google so this would be a pretty nice solution, especially if we can send the user's default language as the target language in the request.

![IMG_2691](https://github.com/liftoff-app/liftoff/assets/7827009/5200e5f5-f7c4-4742-b0d3-b10bf7ee7c04)

And it looks like it's all doable in the URL: https://translate.google.com/?sl=de&tl=en&text=es%20arbeitet

Looks like this could be quite a simple change if Lemmy is using the same language ids as google.
