### ISSUE TITLE
Improvements to double tap to exit behavior

### ISSUE THREAD

**Issue by jordan1776** [liftoff-app/liftoff#104]
### Is your feature request related to a problem? Please describe.

I like that #24 was implemented but I noticed the way it is done is it puts the action at the root of all pages (home, communities, search, and profile), which is not the I think it should be done.

### Describe the solution you'd like

Pressing back from the root of communities, search, and profile should go to the home screen. Pressing back again should start the double tap action (with toast/popup), pressing a third time (relative from starting at the profile screen, for example) would close the app.

Also the popup covers up the nav bar, maybe a bubble floating slightly above would be better?

### Describe alternatives you've considered

None.

### Additional context

![Screenshot_20230626-200150_1](https://github.com/liftoff-app/liftoff/assets/6100101/fdb6bc8a-fc06-4da0-9059-66d672443ea6)

**Comment by zachatrocity** [comment]
Yup, after playing with it I had the same thought. Thanks for logging, will take a look!

**Comment by lemmygod** [comment]
I'd consider adding an x to close the toast.

**Comment by jordan1776** [comment]
> I'd consider adding an x to close the toast.

I was thinking more of instead of it being an element on top of the screen, it should be an actual toast notification that floats on the screen[ like this](https://forumstatic.oneplusmobile.com/opforum-gl/upload/image/front/thread/20220615/190658/1089250644604747780/1089250644604747780.jpg). In this way, there wouldn't need to be an x to close it.

**Comment by lemmygod** [comment]
Yes. In other apps, you can even click elements behind it. It doesn't need to be solid, and it doesn't need to block what's behind it.
