### ISSUE TITLE
User and community link handling issues

### ISSUE THREAD

**Issue by jordan1776** [liftoff-app/liftoff#107]
### Device info

- OS: Android 
- OS version: 11
- Device: Xperia 1 II 
- Liftoff version: 

### Describe the bug

!community@instance.com, /c/ (raw), and c/ links open as emails instead of going to the community in app

Also @username@instance.com links open as emails links and do not go to the users page.

And strangely, taping the link given by the share dialog for a user gives the error "couldn't open link, unimplemented error: need to create userprofile constructor first".

Full links for communities work except when the main instance is one you have have logged in (goes to browser).

 The share for a community works fine.

### Steps to reproduce

1. Go to any post or comment where has @user@instance.com, /c/ (not in a hyperlink), c/,  !community@instance.com 
2. Click on the link
4. See issue

### Expected behavior

These links should link in app as intended.

### Additional context

https://lemmy.ml/post/1477054

**Comment by zachatrocity** [comment]
Hey @jordan1776  I just wanna say how much i appreciate you helping bug test and add/triage issues. Are you on the matrix?

**Comment by jordan1776** [comment]
Thanks, I didn't notice there was a matrix, i'll join it
