### ISSUE TITLE
Lemmy Api Exception 

### ISSUE THREAD

**Issue by seelebrn** [liftoff-app/liftoff#125]
### Device info

- OS: [Android]
- OS version: [9]
- Liftoff version: [0.9.18]

### Describe the bug

Maybe it's the expected behavior, but it seems account settings aren't being saved. It's been that way for 3 or 4 days, so it doesn't seem to be a temporary lemmy hiccup. 

Note : it was likely the cause for #52. Although I didn't see/notice the error msg at that time, I solved my issue by logging into lemmy.world from my browser and disabling "Show read posts" from there, after which everything worked as expected. 

### Steps to reproduce

-Change your account settings (i.e : enable "Show Read Posts") 
-Press "Save" 
-The error pops up
-Re-enter the account menu 
-"Show read posts" is still disabled 

### Relevant logs
![Screenshot_20230628_070719](https://github.com/liftoff-app/liftoff/assets/61107208/72b11ce3-795b-4d2c-bf78-1dfc2af13133)

**Comment by mykdavies** [comment]
Looks like another issue with the new Lemmy version. Looping in @zachatrocity.

**Comment by swmarks** [comment]
@mykdavies and @seelebrn just out of curiosity which instances are you all having this issue on? I'm not having luck reproducing this behavior on my personal instance (presently on v0.18.1rc2) or Lemmy.ml (presently on v0.18.0). I'm wondering if this is a v0.17.x and below thing.

**Comment by seelebrn** [comment]
Yes indeed. I'm on Lemmy.world, so v0.17.x !

**Comment by mykdavies** [comment]
Same here so maybe we can just wait out way out of this :-)
