### ISSUE TITLE
"Mark as seen"/"Mark as read" for the feed

### ISSUE THREAD

**Issue by mykdavies** [liftoff-app/liftoff#130]
### Is your feature request related to a problem? Please describe.

A few users have asked for the feeds to remember which posts and comments the user has already seen and mark or hide them in some way.

### Describe the solution you'd like

A few users have asked for the feeds to remember which posts and comments the user has already seen and mark or hide them.

I imagine this would work by keeping a local log of the last time the user viewed each feed, and a list of posts they have viewed with the timestamp, and matching these up before deciding what to show and how to present it.

**Comment by zachatrocity** [comment]
We should use the out of the box Lemmy functionality for this. Implementing our own log would be error prone.

Lemmy has an option in user settings for this:

![Screenshot_20230628-060359.png](https://github.com/liftoff-app/liftoff/assets/6200670/1f30bdb3-a9be-439c-9bb0-6308e9294dad)

I'm not sure how well or if it works.
