### ISSUE TITLE
App hangs/crash on posts with hundreds of comments (possible memory leak)

### ISSUE THREAD

**Issue by Generator** [liftoff-app/liftoff#132]
### Device info

- OS: Android
- OS version: 13
- Device: Xiaomi Redmi Note 8T
- Liftoff version: v0.9.18

### Describe the bug

Posts with hundreds (900+) comments the app hangs or crash.
First time the app hang and closed manually, the second time the app hang and rebooted the OS.

### Steps to reproduce

1. Open the post https://lemmy.world/post/45688

### Additional context
Phone have 4GB RAM

**Comment by Generator** [comment]
Also tested the app on linux (Manjaro), it goes from ~440MB to 1GB after opening that post.  
The app didn't crash or hang on linux

**Comment by mykdavies** [comment]
Just checked on iOS and it opened it once but got very janky, and on opening again the app crashed.

**Comment by zachatrocity** [comment]
dup of #51
