### ISSUE TITLE
Add sort posts "Top 1h/6h/12h"

### ISSUE THREAD

**Issue by Generator** [liftoff-app/liftoff#139]
### Is your feature request related to a problem? Please describe.

Add a sort post by "Top Hour/Six/Twelve" Hours like in the WebUi.

### Describe the solution you'd like
Similar like the Lemmy-UI

![ksnip_20230628-145159](https://github.com/liftoff-app/liftoff/assets/44146/93b889a2-2ad3-4df5-acf0-5767cba05fe2)

**Comment by jcgurango** [comment]
As far as I understand, this would first need to be implemented in Lemmy itself, since sorting is done on the server end. I suppose a client side version could be implemented by further filtering "TopDay" but I think that would use quite a lot of bandwidth.

**Comment by Generator** [comment]
And it was
Backend:  https://github.com/LemmyNet/lemmy/pull/3161
Frontend: https://github.com/LemmyNet/lemmy-ui/pull/1345

**Comment by SigurdVie** [comment]
This is a must have!
