### ISSUE TITLE
Failure to login to `beehaw.org` - `LemmyAPIException: password_incorrect`

### ISSUE THREAD

**Issue by franciscoreinolds** [liftoff-app/liftoff#141]
### Device info

- OS: Android
- OS version: 13
- Device: Google Pixel 6
- Liftoff version: v0.9.18

### Describe the bug

Upon attempting to sign in after copying my login credentials from KeePassXC, a `LemmyAPIException: password_incorrect` prompt appears.

### Steps to reproduce

1. Go to the `Accounts`tab;
2. Click on `Add account`;
3. Select `beehaw.org`;
4. Fill in credentials (no TOTP, maybe this is related?);
5. Click `Sign in`;
6. See error;

### Relevant logs

No logs were produced.

### Expected behavior

That the login would be successfully completed.

**Comment by mykdavies** [comment]
We've seen a problem with passwords with spaces in them--do you have any unusual characters in your password?

I think I saw a reference to Beehaw having problems earlier today, so it may be worth trying again. I'm able to log on okay at the moment.

**Comment by franciscoreinolds** [comment]
> We've seen a problem with passwords with spaces in them--do you have any unusual characters in your password?

Indeed, a lot and all sorts of characters, spaces included.

> I think I saw a reference to Beehaw having problems earlier today, so it may be worth trying again. I'm able to log on okay at the moment.

I also noticed that, but that behaviour seemed more timeout related (aka, submitting credentials and never logging in, instead of some prompt popping up), so I don't really know what to make of it.

---

Should I just try to change my password to one without spaces and try again? 😅

**Comment by mykdavies** [comment]
Thank you, that's very helpful. Sounds like there certainly is something here we need to understand.

**Comment by swmarks** [comment]
OH, I know this one! Lemmy doesn't support 64 character passwords. The server only supports 60 characters. We should truncate our password field, but this should also be made more clear to users when they're signing up on instances. @franciscoreinolds try generating a new 60 character password without spaces and that will likely work.

**Comment by mykdavies** [comment]
Nice catch! Does that mean the lemmy servers are silently truncating user passwords? oof.

**Comment by swmarks** [comment]
> Nice catch! Does that mean the lemmy servers are silently truncating user passwords? oof.

I would assume so, but clients should be sanitizing their fields somewhat too. Like [lemmy-ui has a max length defined](https://github.com/LemmyNet/lemmy-ui/blob/4674f6ff57fbf705246da76c46d3bd5add779228/src/shared/components/home/login.tsx#L106C21-L106C21) and [Jerboa appears to be truncating](https://github.com/dessalines/jerboa/blob/aaad47c5cab064dede28e4ef1debec058ef73cdb/app/src/main/java/com/jerboa/ui/components/login/Login.kt#L115).

**Comment by zachatrocity** [comment]
Fixed in #146

**Comment by franciscoreinolds** [comment]
Can confirm that changing the password to <60 characters has indeed done the trick!

Thanks for the insight and the fix! ❤️
