### ISSUE TITLE
nsfw communities show no posts 

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [liftoff-app/liftoff#144]
### Device info

- OS: android
- OS version: 13
- Device: galaxy s22
- Liftoff version: 0.9.18

### Describe the bug

When searching for a nsfw community I can see posts in the Posts feed, but if I try to open the community it shows no posts. This happens across multiple instances

### Steps to reproduce

1. Search for boobs
2. See all the posts 
3. Try to open the community from a post, or even from the communities search tab
4. Shows no posts, but switching to comments in the community shows comments

### Expected behavior

Should show me all posts in the community

**Comment by zachatrocity** [comment]
I've already done a couple different community fixes. I'll fix this one too. 

![mr-bean-wink-wink](https://github.com/liftoff-app/liftoff/assets/6200670/2d168c38-04d4-4d5b-b696-2ba3951dc4dd)

**Comment by TurnItOff-OnAgain** [comment]
No rush. There are.. Uh... Other ways to see that content

![giphy](https://github.com/liftoff-app/liftoff/assets/26926284/4708d3a2-a531-4f63-b680-7d7e849bc55a)

**Comment by zachatrocity** [comment]
This is due to API changes. We need to implement:

https://github.com/LemmyNet/lemmy/issues/3014

**Comment by zachatrocity** [comment]
Actually I'm thinking this won't work through Lemmy.world until they update to 18.1.

@swmarks are you federated with Lemmynsfw on your 18.1 instance? If so could you test this?

**Comment by Alaric323** [comment]
This seems to have broken something in kbin federation; I can see posts on some nsfw lemmy instances (lemmynsfw for example) from my home instance (Fedia.io), but they are three weeks old, before this patch went live.  All newer posts are hidden.

This could easily be a kbin issue of course, but given other issues of posts and entire communities being invisible when browsing the direct instance, this could still be a Lemmy issue.  Why are entire communities hidden on an NSFW instance?  That just makes people think they don't exist and drives newcomers away, especially escapees from Reddit.
