### ISSUE TITLE
Can't open links posted from Kbin in the internal webview

### ISSUE THREAD

**Issue by FriederHannenheim** [liftoff-app/liftoff#158]
### Device info

- OS: Android
- OS version: 12
- Device: OnePlus 8T
- Liftoff version: v0.9.18

### Describe the bug

When opening urls posted on Kbin in Liftoff, a "Web page not available" error is shown with the subtext "ERR_CLEARTEXT_NOT_PERMITTED"

### Steps to reproduce

Open this post in Liftoff: https://lemmy.one/post/559402 (can be found by searching for "GMail is breaking Email")
Click on the Url

### Expected behavior

The webpage should show correctly

**Comment by Maarten-buelens** [comment]
I had the same problem. It is because the webpage is http not https and the webview does not allow http. I dont know if it is supposed to be this way.

**Comment by zachatrocity** [comment]
Kbin should support https and it's a little embarrassing if they dont. Closing
