### ISSUE TITLE
back swipe interferes with swiping in communities

### ISSUE THREAD

**Issue by jordan1776** [liftoff-app/liftoff#160]
### Device info

- OS: Android
- OS version: 11
- Device: Xperia 1 II
- Liftoff version: 0.9.18

### Describe the bug

When swiping between posts, comments and about in a community, the swipe back gesture is too easily actives. And if your not careful, you can lose your place in the feed.

### Steps to reproduce

1. Go to a community
2. Swipe right-to-left to "about"
3. Try swiping left-to-right to posts without activating back swipe gesture.

### Expected behavior
The back gesture shouldn't be so easy to activate especially in a page where a similar gesture is being used. Maybe reduce the portion of the screen for the back gesture to 20% of the left side.

### Additional context

I still believe there should be a reverse gesture on the opposite side to go back to the page and position you were on before. #46

**Comment by zachatrocity** [comment]
I believe this was fixed. The gesture isn't captured within the tab controller

**Comment by jordan1776** [comment]
Thanks, after testing it in 0.10.4 it seems to be fixed for instances, but not in communities. Also very minor thing, the edge swipe is a little hard to use on a phone with a case on. Thanks!

**Comment by jordan1776** [comment]
Also, the user page as well.
