### ISSUE TITLE
Tap images to close and return to the thumnail view

### ISSUE THREAD

**Issue by ghoool** [liftoff-app/liftoff#161]
### Is your feature request related to a problem? Please describe.

Tapping on a thumbnail expands it but the close X button is up the top of the screen.

### Describe the solution you'd like

Tap thumbnails to expand to full image. Tap anywhere on screen to close the full image view and return to thumbnail/post view.

Joey for Reddit does it and it works really well.

**Comment by TurnItOff-OnAgain** [comment]
You can swipe the image away as a workaround

**Comment by ghoool** [comment]
@TurnItOff-OnAgain Cheers, am aware of that.  This is an enhancement request to make it even better, since people's thumbs get lazy.  :)

**Comment by zachatrocity** [comment]
Good first issue if you're interested in contributing!

Otherwise low on the priority list right now
