### ISSUE TITLE
Post with markdown footnotes gets all grey

### ISSUE THREAD

**Issue by Generator** [liftoff-app/liftoff#162]
### Device info

- OS: Android
- OS version: 13
- Device: Xiaomi Redmi Note 8T
- Liftoff version: v0.9.18

### Describe the bug

Posts with [footnotes](https://docs.github.com/pt/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#footnotes) only display in grey 

### Steps to reproduce

1. Open post https://lemmy.pt/post/556709

### Expected behavior

Render markdown with footnotes
![Screenshot 2023-06-29 at 14-36-45 List of Reddit apps working after June 30 - Lemmy Português](https://github.com/liftoff-app/liftoff/assets/44146/8ffba632-ad87-415b-899e-49d56c7d32c1)

### Screenshots/Screencasts

![Screenshot_20230629-143206_crDroid Home](https://github.com/liftoff-app/liftoff/assets/44146/1d7e98b8-36d9-4d7a-87fc-404581aee7f6)

**Comment by zachatrocity** [comment]
This is fixed in the latest release building now:

https://github.com/liftoff-app/liftoff/actions/runs/5413095145
