### ISSUE TITLE
Make the feed change to the first instance the user logs in on

### ISSUE THREAD

**Issue by Blackilykat** [liftoff-app/liftoff#163]
When you first open the app you are in the EVERYTHING feed, which is disabled by default. This doesn't change when you log in and leaves confused until you realise that the feed you're on isn't on the visible list.

When the user first logs in, set the feed to All on the instance they logged in 

Have one single default instance so that it's shown at the top and it's clear what feed you're in

**Comment by zachatrocity** [comment]
This has just been fixed in the latest release. 0.9.19
