### ISSUE TITLE
Replying to a comment with existing replies appears to duplicate existing replies

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [liftoff-app/liftoff#167]
### Device info

- OS: android 
- OS version: 13
- Device: galaxy s22
- Liftoff version: 0.9.19

### Describe the bug

When replying to a comment that already has replies, it appears to duplicate an existing reply until you refresh

Ex:

This is comment A
    This is a reply to comment A

If I reply to comment A it appears to duplicate the existing reply until I refresh the post, then my reply appears

### Steps to reproduce

1. Reply to a comment that already has a reply on it

### expected results

The comment I posted should show along with existing replies.

### Screenshots/Screencasts

https://ibb.co/WtvZ5tZ

**Comment by njmdietrich** [comment]
I can report that I have the same issue, also on android 13

**Comment by zachatrocity** [comment]
@jcgurango this seems related to the duplicate comment fix you had earlier. Any ideas?
