### ISSUE TITLE
Votes don't show on community pages

### ISSUE THREAD

**Issue by arshadrr** [liftoff-app/liftoff#172]
### Device info

- OS: Android
- Liftoff version: v0.9.18

### Describe the bug

Votes I have made show up fine on the home tab ("subscribed", "local" and "all") and account tab for posts (from communities on both local and external instances.)

Tapping through to a community, (on the local instance or not) votes I've made don't show up. Viewing the comments makes it show up, and returning to the feed for the community ("active", "hot", etc.) it correctly show but only for the post I viewed comments.

Votes on comments that show under the "comments" tab for a community are loaded fine.

### Steps to reproduce

1. Go to the page for a specific community and vote on a post.
2. Switch to another tab then return to the specific community. The vote made doesn't show.

**Comment by zachatrocity** [comment]
Fixed with the fixes for NSFW communities
