### ISSUE TITLE
Color picker for votes.

### ISSUE THREAD

**Issue by rareromfish** [liftoff-app/liftoff#173]
### Is your feature request related to a problem? Please describe.

I struggle to see the upvote color, the light green is very similar to the gray of dark mode.

### Describe the solution you'd like

I would really like to be able to pick my own colors for upvotes and downvotes. Some kind of color picker, or something basic like a hex code input would be very nice.

### Describe alternatives you've considered

I'm not sure what other solutions would be better, I suppose the light green could be swapped for another hard coded color? I'd still prefer to be able to pick my own vote colors if possible.

### Additional context

Screenshot of how it currently appears on my screen:

![image](https://github.com/liftoff-app/liftoff/assets/42591800/f8b0799c-2bd1-414f-9ce5-ce20bac43863)

**Comment by jordan1776** [comment]
What about a few preset options like purple/dark orange, orangered/periwinkle, green/red, and the current cyan/red?

**Comment by JonathaN7Shepard** [comment]
This is my #1 usability issue right now. Hoping it gets prioritized.

**Comment by zachatrocity** [comment]
This will come in the comment style settings page. We'll pair this issue with other comment view settings

**Comment by swmarks** [comment]
> This will come in the comment style settings page. We'll pair this issue with other comment view settings

Yeah, if you're considering what to do for defaults, I would maybe recommend default colors match lemmy-ui. I definitely would prefer up/downvotes to be different colors from each other and distinct from the primary accent color (as it appears to be presently).

**Comment by mykdavies** [comment]
Closed with PR #295

**Comment by mykdavies** [comment]
Closed with PR #295
