### ISSUE TITLE
Submit to accrescent

### ISSUE THREAD

**Issue by tcely** [liftoff-app/liftoff#176]
### Is your feature request related to a problem? Please describe.

Installing from GitHub isn't a safe strategy.

### Describe the solution you'd like

Android has several stores available that will greatly improve the installation user experience.

### Describe alternatives you've considered

- [x] Google Play Store
- [ ] F-Droid (Covered by #47)
- [ ] Accrescent

### Additional context

https://accrescent.app/docs/guide/publish/getting-started.html

**Comment by zachatrocity** [comment]
I've never heard of Accrescent. And it doesn't look super... mature.

F-Droid and play store are probably all we will support unless you want to contribute.

Installing from GitHub via obtainium is a safe enough strategy for people who want the bleeding edge releases.

Going to close, I can reopen if this is something you'd like to contribute.
