### ISSUE TITLE
Profile editing causes JSON deserialization error

### ISSUE THREAD

**Issue by AngelaVilladiego** [liftoff-app/liftoff#185]
### Device info

- OS: Android
- OS version: 13
- Device: Samsung Galaxy S21 5G
- Liftoff version: v0.9.19

### Describe the bug

When going to edit profile, any changes made including uploading an avatar, uploading a banner image, or switching off "Show read posts" causes an error toast with the following text to appear:

![Error toast](https://github.com/liftoff-app/liftoff/assets/49819113/dea9ed64-f6b9-408d-8b9a-699a21d12eba)

### Steps to reproduce

1. Go to profile on bottom right
2. Click on "edit profile"
3. Make any change
4. Scroll down
5. Click "save"
6. See error

### Relevant logs

No logs when I go to settings > about liftoff > logs.

### Expected behavior

A confirmation my changes were saved and sent and being returned to the previous page with my changes active.

### Screenshots/Screencasts
 
![Screenshot as above of error toast](https://github.com/liftoff-app/liftoff/assets/49819113/dea9ed64-f6b9-408d-8b9a-699a21d12eba)

### Additional context

The first thing I did when going to the settings was try to add an avatar image. Not sure if there are requirements for file size and messed up future API requests this way.

**Comment by zachatrocity** [comment]
This has been resolved
