### ISSUE TITLE
Optimistic UI for up/downvotes (0.9.19 android)

### ISSUE THREAD

**Issue by adrian-sal-kennedy** [liftoff-app/liftoff#189]
I've noticed upvoting takes about 3 seconds where I am (android if that makes a difference).

Though an activity indicator is shown, it would make more sense to optimistically just colour the upvote element as if the api call succeeded, then update it again if it somehow doesn't succeed.

**Comment by klueman** [comment]
I believe this is how the web app worked prior to 18.0 and it kind of caused issues. Often times people will vote and scroll on, without going back to check if the vote was counted.

**Comment by zachatrocity** [comment]
Yeah, we're not gonna consider this right now, perhaps once lemmy backend has matured more and things are more predictable between minor releases.

Going to close for now.
