### ISSUE TITLE
The "+" in the middle bottom of the up is too big and I don't like how it takes up my screen space.

### ISSUE THREAD

**Issue by M4rtineski** [liftoff-app/liftoff#197]
### Is your feature request related to a problem? Please describe.

The "+" in the middle bottom of the up is too big and I don't like how it takes up my screen space.

### Describe the solution you'd like

I want a setting that would allow the "+" to be more compact and be of size of the rest of the buttons and in the same line as them without getting out of the bottom button bar or whatever it is called.

### Describe alternatives you've considered

I want either for it to be optional or hard coded.

### Additional context

No add context

**Comment by jordan1776** [comment]
when #43 is fully completed both top and bottom bars should disappear on scroll so that large + is only there when you need it.

**Comment by M4rtineski** [comment]
Ty for info.

**Comment by M4rtineski** [comment]
closing
