### ISSUE TITLE
Subscribed@All

### ISSUE THREAD

**Issue by wargreymon2023** [liftoff-app/liftoff#199]
Having different communities on different instances subscribed is the default behaviour of users, bc not all instance is federated.

If I were to view all of my subscription as usual, currently i would have to check across all instance instead of a nice list at the front page.

This problem is very noticeable right now, bc most of the front page(All@instance) is about Reddit, I would rather read my subscription, namely subscribed@All.

**Comment by zachatrocity** [comment]
Enable the everything feed in the settings then use everything -> subscribed

**Comment by wargreymon2023** [comment]
Didn't notice that, thanks
