### ISSUE TITLE
Request for a setting to always links open in external browser

### ISSUE THREAD

**Issue by DeltaTangoLima** [liftoff-app/liftoff#23]
### Is your feature request related to a problem? Please describe.

Currently, clicking on a link in a post opens the link in an internal browser, meaning none of the usual benefits of using a chosen browser are available (eg. bookmarking, etc).

### Describe the solution you'd like

A setting that lets me tell Lemmynade to use my external browser when opening any links.

### Describe alternatives you've considered

Tried opening the post itself in the browser using the overflow menu, but this had unpredictable results. ~~It seemed to open using the Alexa personal assistant app instead! (I will investigate this some more before asserting it's an actual issue with the app)~~

Correction: looked like a bug in my launcher showing the wrong icon. The overflow menu option to open in browser still only uses the internal browser in Lemmynade.

**Comment by DraconicNEO** [comment]
I second this issue, it's really frustrating to try and open a link to just have it open in the built-in browser instead of allowing me to open it in my main browser. Especially when the link is to download something.

**Comment by swmarks** [comment]
There is an option to do this under Settings > General
