### ISSUE TITLE
Add the ability to change the font size of comments

### ISSUE THREAD

**Issue by AppleSheeple** [liftoff-app/liftoff#230]
### Is your feature request related to a problem? Please describe.

#108 added the ability to change font sizes in posts, but not comments.

### Describe the solution you'd like

Add an option to change the font size of comments.

### Describe alternatives you've considered

None

### Additional context

* Post font sizes (title=20, header=18)
![Screenshot_20230703-042721_Liftoff](https://github.com/liftoff-app/liftoff/assets/68065381/e4ee9777-b090-41cc-8bef-16d1d74109e1)

**Comment by jersa** [comment]
Please, thank you!

**Comment by KarkanAlzwayed** [comment]
This is literally the single one reason why I don't use liftoff. My eyes start hurting after a couple of minutes of reading the comments.

**Comment by AppleSheeple** [comment]
This was implemented in #326 and is available in 0.10.7.

Thank you @zachatrocity for implementing this.
