### ISSUE TITLE
Incomplete Russian internationalisation

### ISSUE THREAD

**Issue by ashed** [liftoff-app/liftoff#239]
### Device info

- OS: [Android]
- OS version: [11]
- Device: [Poco X3 Pro]
- Liftoff version: [v0.10.4]

### Describe the bug

Liftoff v0.10.4. has no correct i18n (ru-RU)

### Steps to reproduce

1. Go to 'Settings'
2. Click on 'General'
3. Select 'Русский'
4. See incomplete internationalisation

### Expected behavior

Complete i18n.

### Screenshots/Screencasts

![photo_2023-07-03_14-20-33](https://github.com/liftoff-app/liftoff/assets/6615946/5a870ac7-53df-4854-9e90-4276a58766a5)

### Additional context

I fix and complete translate Liftoff intl_ru.arb.
Add it to upstream, please.

[Liftoff-v0.10.4-intl_ru.zip](https://github.com/liftoff-app/liftoff/files/11936185/Liftoff-v0.10.4-intl_ru.zip)

**Comment by mykdavies** [comment]
Thank you so much for contributing this. We're not where we need to be in ensuring that we use the localisations in all our code, but having up-to-date target language files will be a great encouragement for us to focus on fixing this!

**Comment by ashed** [comment]
okay @mykdavies I fixed absent strings, that 's much better. Thanks for quick replly

[intl_ru-2023-07-08.zip](https://github.com/liftoff-app/liftoff/files/11990405/intl_ru-2023-07-08.zip)

**Comment by mykdavies** [comment]
Lovely stuff. There was a small problem with some entries using formattedCount where you had accidentally translated 'other' which is part of the .arb syntax, but that was easily fixed. This should appear in our next release. Thanks for your hard work!
