### ISSUE TITLE
Go to post (context) link in inbox fails to find correct comment.

### ISSUE THREAD

**Issue by mykdavies** [liftoff-app/liftoff#246]
### Device info

All

### Describe the bug

When I click the go to post button from my inbox I get a post failed to load then one second later liftoff defaults to the main post instead of linked comment.

### Steps to reproduce

As above 

### Expected behavior

Should display the comment in its context.

### Additional context

May have been introduced in recent server software upgrades.

**Comment by jcgurango** [comment]
Gonna close this in favor of #118

**Comment by mykdavies** [comment]
Thanks, I was sure I'd seen the issue reported before but I must have screwed my search up because I didn't find this, despite it having all the right keywords in the title :-)
