### ISSUE TITLE
Open communities with a different instance 

### ISSUE THREAD

**Issue by chersys** [liftoff-app/liftoff#247]
### Is your feature request related to a problem? Please describe.

If you are not logged in to an instance, for example lemmy.world, and you try to subscribe to a community retrieved via lemmy.world, it will tell you that `This thread was retrieved via lemmy.world. You are not logged in there.` There's no easy way to open the community in an instance you're logged in. You can't copy the name by long pressing on `!community@lemmy.world` and paste it in the search bar in an instance you're logged in. Searching for a community by pasting `!community@lemmy.world` in the search bar is currently broken. 

### Describe the solution you'd like

Instead of just telling `This thread was retrieved via lemmy.world. You are not logged in there`, it should offer to open the community in a different instance. Or there should an option to open the community in a different instance in the menu. If it can't find the community locally, It can try to retrieve the community by searching for it. I think this will make it easier to subscribe to new communities in other instances.

**Comment by jcgurango** [comment]
This will be implemented in #251
