### ISSUE TITLE
Error opening the communities tab

### ISSUE THREAD

**Issue by SecondPartySoftware** [liftoff-app/liftoff#248]
### Device info

- OS: Android
- OS version: 12
- Device: Surface Duo 2
- Liftoff version: 0.10.4

### Describe the bug

See screenshot. Error text after tapping on communities button

### Steps to reproduce
1. Tap on the communities button on the bottom bar
2. See error

### Expected behavior

Communities to show up.

### Screenshots/Screencasts

![Screenshot_20230703-082927~2](https://github.com/liftoff-app/liftoff/assets/63615672/efc8c3cb-8471-4799-88ab-14b3c7587e46)

### Additional context

 It has worked previously so may be a transient server issue?

**Comment by jcgurango** [comment]
This is an error on your instance, but we may be looking into implementing some detection for whether an instance is healthy and responding to requests correctly.

**Comment by SecondPartySoftware** [comment]
Gotcha, I'm logged in to lemmy.one and lemmy world. Not sure which one would be throwing the error.
