### ISSUE TITLE
Tap Home to scroll to top

### ISSUE THREAD

**Issue by SecondPartySoftware** [liftoff-app/liftoff#249]
### Is your feature request related to a problem? Please describe.

An easy way to scroll to top. I'm aware of the flyout menu option but this would be even easier. 

### Describe the solution you'd like

Tapping on the Home button when you are already in the feed should scroll to the top instead of having to go through the flyout menu. 

### Additional context
In Boost, I liked the option to automatically mark as read as I scrolled with a command to hide read (not the permanent option). That way I could still revisit things I have seen but still have an easy way to hide them until I refreshed.

**Comment by zachatrocity** [comment]
You can get back to the top by clicking the scroll to top in the 3-dot menu of the nav bar. We're not going to implement this at this time. We feel it would be too easily bumped if it were on the home icon and there would be no way to get back to your place.

**Comment by jordan1776** [comment]
> We feel it would be too easily bumped if it were on the home icon and there would be no way to get back to your place.

Isn't this a solved issue? In the comments view, hitting the title on the top bar goes back to the top, but pressing again goes to where you were. Why can't the post view have the same behavior?
