### ISSUE TITLE
Comments don't appear if there are too many comments

### ISSUE THREAD

**Issue by lemmygod** [liftoff-app/liftoff#26]
### Device info

- OS: Android
- OS version: 12
- Device: Galaxy A52
- Lemmynade version: v0.9.6

### Describe the bug

Comments don't appear if there are too many comments.

See the gray part in this 576 comment post:

url: https://lemmy.world/post/373743

![image](https://github.com/zachatrocity/lemmynade/assets/137420192/a95fdea5-fe41-426b-afb2-6e3b052b4f34)

**Comment by zachatrocity** [comment]
This is actually the comments not appearing if there is a pinned comment. Found the issue due to the restructuring of the lemmy api
