### ISSUE TITLE
Some images become scrollable and it negatively effects scrolling experience

### ISSUE THREAD

**Issue by chersys** [liftoff-app/liftoff#260]
### Device info

- OS: Android
- OS version: 13
- Device: Pixel 7
- Liftoff version: 0.10.4

### Describe the bug

Some images become scrollable independent of the feed. When you scroll the images up and down, only the images scroll up and down, not the feed. This negatively impacts the scrolling experience by stopping the movement of the feed. To move the feed again, you have to scroll from a part of the screen that's not the image. This happens sometimes if images are too long or if there are multiple images in a post. 

For example, see [this post](https://lemmy.world/post/1004346).

### Steps to reproduce

1. Find a post with a scrollable image in a feed
2. Swipe up or down with your finger on the image
3. Only the image goes up and down

### Expected behavior

The feed should continue to move after the image stops moving

**Comment by chersys** [comment]
I noticed that this happens when the image urls are in the body of the post

**Comment by shocklateboy92** [comment]
That's actually the body of the text, rather that the media.
It gets addressed by #286
