### ISSUE TITLE
Account Syncing

### ISSUE THREAD

**Issue by sanicki** [liftoff-app/liftoff#269]
### Is your feature request related to a problem? Please describe.

Migrating between Lemmy instances is not trivial for users with extensive community subscription lists, block lists, etc.

When an instance is struggling (performing a Lemmy upgrade, getting hugged by Reddit refugees, etc.) then having a mirror account on another server is also useful.

### Describe the solution you'd like

Have the ability to tag accounts as `default`, `alt`, or `mirror`.

There could be only one `default` account.

Accounts tagged as `alt` would be distinct.

Accounts tagged as `mirror` would sync profile settings, subscribed communities, block lists, etc. from the `default` account.

### Describe alternatives you've considered

[This Python script](https://github.com/Ac5000/lemmy_account_sync) syncs profile settings, subscribed communities, and block lists, but it requires some knowledge to set up that the average Lemmy user may not have.

### Additional context

I imagine this feature living in Settings under Accounts.

![Screenshot_20230704-114016](https://github.com/liftoff-app/liftoff/assets/6764844/a3b6cb62-b153-45c5-b438-c643effe51c2)

**Comment by zachatrocity** [comment]
This would be a great feature! However a 3rd party app is not the place to implement this safely and correctly.

This would need to be implemented in lemmy backend. They're having discussions about ability to move accounts between instances, syncning could be accomplished in a similar way.
