### ISSUE TITLE
Allow opening links in external applications

### ISSUE THREAD

**Issue by lemmygod** [liftoff-app/liftoff#28]
### Is your feature request related to a problem? Please describe.

YouTube opens in browser. 

Spotify too.

That means I can't play the content very well.

### Describe the solution you'd like

Either by default or at least an option in the settings, allow to open any link not to lemmy in an external app.

**Comment by FriederHannenheim** [comment]
Yes please add an option for this. Since the internal browser for liftoff has no on-screen controls, websites can make it impossible to leave. I clicked on a yahoo link and I had to restart the app because the back button kept redirecting to the same site
