### ISSUE TITLE
Endless loading loop when trying to log in

### ISSUE THREAD

**Issue by Thedarkfly** [liftoff-app/liftoff#29]
### Device info

- OS: Android
- OS version: 11
- Device: Fairphone 3+
- Lemmynade version: 0.9.6

### Describe the bug

After entering the credentials to connect to a Lemmy account and pushing the "Sign in" button, a loading animation starts and loops indefinitely.

### Steps to reproduce

1. Go to the "Add account" page
2. Select the feddit.nl instance
3. Enter credentials of account
4. Push on "Sign in" button

### Relevant logs

"No logs" displayed in Logs page.

### Expected behavior

Successful sign into account, or display of an error message if something went wrong.

### Screenshots/Screencasts

![Screenshot_20230623-143133](https://github.com/zachatrocity/lemmynade/assets/6185837/ff95fb34-0286-4d64-9b7e-7c7dbbec233f)

### Additional context

Maybe instance-dependant? I tried to input both my email and my username.

**Comment by tiritibambix** [comment]
Same problem


    OS: Android
    OS version: 12
    Device: OnePlus Nord2 5G
    Lemmynade version: 0.9.6

**Comment by Canning** [comment]
Same problem with sh.itjust.works. Beehaw and lemmy.world work fine.

**Comment by zachatrocity** [comment]
The problem is 0.18.0 release. Instances on 0.18.x dont play nicely from an API point of view with 0.17.x, there were some breaking changes in the api. Working on a fix should be released soon.

**Comment by zachatrocity** [comment]
That was a doozy. 

This has been fixed here: https://github.com/liftoff-app/liftoff/releases/tag/v0.9.11 

Please try the new release. 

@Canning @tiritibambix @Thedarkfly fyi
