### ISSUE TITLE
Make tapping on a comment collapse it (instead of holding)

### ISSUE THREAD

**Issue by NicoCharrua** [liftoff-app/liftoff#30]
### Is your feature request related to a problem? Please describe.

Tapping a comment does nothing, but pressing and holding on a comment collapses it. It makes browsing comments a bit slower and more annoying.

### Describe the solution you'd like

Tapping a comment would collapse it

### Describe alternatives you've considered

This could be an option in the settings but I can't think of any reason why someone would want to hold instead of tap.

**Comment by theboomr** [comment]
Ooh yes I very much agree with this, would love to collapse with a quick tap

**Comment by shocklateboy92** [comment]
Oaf. Please make that behavior optional/configurable if you implement this.
I would expect tapping a comment to select it - disappearing instead wouldn't do nice things to my brain.

**Comment by zachatrocity** [comment]
Yeah this could be an option/configurable.

Boost for reddit had this capability and it was really nice.

**Comment by waldyrious** [comment]
This issue can be closed now that a single tap now collapses a comment (since #96). I have opened a separate issue asking to make the behavior configurable: #267

**Comment by mykdavies** [comment]
Now implemented. Thanks!
