### ISSUE TITLE
Add ability to block a community from the feed instead of needing to navigate to it first 

### ISSUE THREAD

**Issue by SecondPartySoftware** [liftoff-app/liftoff#322]
### Is your feature request related to a problem? Please describe.

There is a block user in the menu already, it would be nice to block community too without needing to navigate to it

### Describe the solution you'd like

Put block community in the post menu you get while scrolling through the feed

**Comment by Inovvia** [comment]
Hi, this will be available in the next release. Here's the PR that solved this -  #206.

Kindly close this issue thank you!

**Comment by SecondPartySoftware** [comment]
Thank you! 

> Hi, this will be available in the next release. Here's the PR that solved this - #206.
> 
> Kindly close this issue thank you!
