### ISSUE TITLE
Forum Thread Comment Sorting

### ISSUE THREAD

**Issue by trymeouteh** [liftoff-app/liftoff#323]
Adding a toggle button on every single post called "Forum" or something like it to sort the comments by date and from oldest to newest. And for comments that are commenting on other comments to have a link to the parent comment and the parent comment in quotations in the comment child comment.

And to also have a setting in the app to have all threads sort comments this way if the user chooses without needed to press the "Forum" button every time.

https://github.com/LemmyNet/lemmy-ui/issues/602

**Comment by zachatrocity** [comment]
Not going to support this unless Lemmy API supports it out of the box.
