### ISSUE TITLE
Release IPA file for iOS

### ISSUE THREAD

**Issue by dtantono** [liftoff-app/liftoff#328]
### Is your feature request related to a problem? Please describe.
I understand that Testflight have a limited capacity and sometimes new users that want to try this app have this limitation

### Describe the solution you'd like

it will be better if you release an IPA file So, users that cannot download this app can sideload it manually and can help testing the app
What do you think?

**Comment by mykdavies** [comment]
Hi, thanks for thinking of this, but we've got plenty of spare slots in TestFlight at the moment. We'll bear it in mind if that does change though. I will close this for now.

**Comment by mykdavies** [comment]
Hi, thanks for thinking of this. We've actually got plenty of capacity in our TestFlight right now, and expect that pressure will ease once we release a version to AppStore, so it's not something we need to do right now. 

I'm going to close this, but will bear it in mind as a useful idea if things do change.
