### ISSUE TITLE
Add support for redgifs

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [liftoff-app/liftoff#333]
### Describe the solution you'd like

Redgifs should be supported inline without having to open content in the browser.

This can be achieved using the [Redgifs REST API](https://i.redgifs.com/docs/index.html)

**Comment by jjcomer** [comment]
Looks like the app would need an API key in order to utilize the REST API. Something to look into.
Potentially (we'd have to look at the ToS) we could enable storing personal account creds and making the requests on your behalf

**Comment by jjcomer** [comment]
This will also need #332
