### ISSUE TITLE
Cannot login to beehaw

### ISSUE THREAD

**Issue by phareous** [liftoff-app/liftoff#342]
### Device info

- OS: [eg. iOS/Android] iOS
- OS version: [eg. 10] 16.5.1
- Device: [eg. OnePlus 6] iPhone 12 mini
- Liftoff version: [eg. v1.2.3]

### Describe the bug

Can’t login to beehaw. It just spins indefinitely

### Steps to reproduce

Go to accounts
Fill out login info to beehaw

### Relevant logs

<details>
  <summary>Logs</summary>
  
  Paste your logs here. Logs can be found in liftoff: settings > about liftoff > logs.
</details>

**Comment by phareous** [comment]
V 0.0.1
It says I have no logs

**Comment by mykdavies** [comment]
V 0.0.1? That's very old, could you go to [this post](https://lemmy.world/post/1185439) and follow the instructions there to load a newer version, and let us know if that helps?

**Comment by phareous** [comment]
Thank you, I had someone fallen off of TestFlight and it wasn’t being updated. Readded and all is working
