### ISSUE TITLE
Clicking on a sublemmy without a leading slash opens my email app?

### ISSUE THREAD

**Issue by HEPOSHEIKKI** [liftoff-app/liftoff#357]
### Device info

- OS: Android
- OS version: 12
- Device: Nokia 5.4
- Liftoff version: 0.10.7

### Describe the bug

Clicking on a sublemmy without a leading slash (eg. /c/fediverse vs. c/fediverse) opens my mail app and throws a toast error which I am unfortunately unable to catch or copy paste.

### Steps to reproduce

1. Find a link to a sublemmy without a leading slash (one can be found in the 'about' section of https://lemmy.ml/c/collapse)
2. Click on the link (on the collapse page, it is the link 'c/collapse@sopuli.xyz'
3. Your mail app should open
4. Switch back to liftoff and see the error toast

### Expected behavior

Allow parsing sublemmy links without a leading slash, or dont, but this shouldn't cause my email all to open.

### Screenshots/Screencasts

[Screenshot of the toast](https://files.catbox.moe/a0ivlq.png)

### Additional context

I hope this isn't related to the XSS vulnerability a day-ish ago?

**Comment by michaelBelsanti** [comment]
The correct method of linking to another community on lemmy is like this: `!collapse@sopuli.xyz`

The links used in that about section are using an incorrect format, and due to the text@domain.com format, they are assumed to be an email address. I would recommend letting the moderators of that community know about the ! format, as it is what should work on all Lemmy instances and apps.

**Comment by HEPOSHEIKKI** [comment]
> The correct method of linking to another community on Lemmy is like this: !collapse@sopuli.xyz
> 
> The links used in that about section are using an incorrect format, and due to the text@domain.com format, they are assumed to be an email address. I would recommend letting the moderators of that community know about the ! format, as it is what should work on all Lemmy instances and apps.

Oh yeah this makes sense, my bad.

**Comment by mykdavies** [comment]
Are you happy for this to be closed at this point given @michaelBelsanti's helpful reply?

**Comment by HEPOSHEIKKI** [comment]
Closing as expected behavior
