### ISSUE TITLE
Subscribed communities with the same name on different instances defaults to the one with the most users.

### ISSUE THREAD

**Issue by Sponholz** [liftoff-app/liftoff#36]
### Device info

- OS: Android
- OS: 10
- Liftoff version: v0.9.11

### Describe the bug

When I subscribe to two communities that share the same name, on the subscribe list it shows two entries, but defaults to the one with the most users.

### Steps to reproduce

As a user logged on lemmy.world instance:
Subscribe to !android@lemmy.ml
Check the list of subscribed communities.
It should show the lemmy.ml community icon and the name, !android@lemmy.ml
Subscribe to !android@lemmy.world
Check the list of subscribed communities.
It should now show two entries with the lemmy.world community icon and name, just Android.
When viewing this communities, the lemmy.ml android community is replaced with the lemmy.world one.

![example-1](https://github.com/liftoff-app/liftoff/assets/30774530/22d88497-29cf-41fa-baaa-bbc73b6b928f)

![example-2](https://github.com/liftoff-app/liftoff/assets/30774530/f3ccbbd4-7170-4916-ae2c-9b7134dba992)

**Comment by qwitwa** [comment]
![Screenshot_20230625_190336_com liftoffapp liftoff](https://github.com/liftoff-app/liftoff/assets/2302478/c1fbafc7-bf11-4954-abae-8407cc289ce8)

Still present on 0.9.12
