### ISSUE TITLE
"Build Removed" on TestFlight?

### ISSUE THREAD

**Issue by seannymurrs** [liftoff-app/liftoff#360]
I've been a member of the TestFlight beta group for Lift-Off. I recently had to wipe my phone, so I've been going through and reinstalling my apps. When I tried to find Lift-Off in TestFlight, it's now listed in the previously tested section of the app. It doesn't say I was removed from the program, but it says build removed next to the app. I can't seem to figure out how to get the current build back on my phone.

**Comment by mykdavies** [comment]
Hi Sean, Can you check you're using the up-to-date TestFlight link: https://testflight.apple.com/join/jKENkGjX ?

There will always be a stickied post on https://lemmy.world/c/liftoff with all the latest instructions for every platform.

**Comment by mykdavies** [comment]
Going to close this. Please feel free to comment if you continue to get this problem.
