### ISSUE TITLE
Portrait photos getting rotated to landscape when uploading

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [liftoff-app/liftoff#379]
When uploading a picture that was taken in portrait it is getting rotated to landscape. Landscape pictures are not rotated.

Rotated portrait pics
https://lemmy.world/post/1423470
https://lemmy.world/post/1423470

Fine landscape pic
https://lemmy.world/post/1423245

**Comment by mykdavies** [comment]
Could you tell us which OS, Device Model, and App Version you're using. This should have been resolved in 0.10.8

**Comment by TurnItOff-OnAgain** [comment]
Android 13

Galaxy s22

I was up to date when I made the issue, I get notifications from github on a new release and install it then. I don't recall the version.

I am on 0.10.9 now and it seems to be fixed.
