### ISSUE TITLE
Make "compact" view properly compact

### ISSUE THREAD

**Issue by CTalvio** [liftoff-app/liftoff#41]
### Is your feature request related to a problem? Please describe.

Compact mode still wastes a lot of screen real-estate. As a comparison, I've included a screenshot of the compact list view of Relay for Reddit.

![image](https://github.com/liftoff-app/liftoff/assets/4365015/103ce6d8-3036-4d93-9ffa-eb1c2b112293)

### Describe the solution you'd like

Something like:
![image](https://github.com/liftoff-app/liftoff/assets/4365015/56739146-0338-4e40-b6aa-9af84071fdb7)

Less padding between posts. Move thumbnail to the left/right, and place no text element's below or above it. Make interact buttons appear on long tap or slide, like in relay.

**Comment by zachatrocity** [comment]
This is related to #27 which will help here. Thanks for the suggestion. Compact View will get better.

**Comment by CTalvio** [comment]
Font could be smaller, but right now for me the biggest concern is all the empty space on screen. There's room for both bigger thumbnails and a more compact text layout, even without changing font size.

**Comment by jordan1776** [comment]
This is what a compact view should be, what you are asking for is a list view, where information density is more important than aesthetics (large padding). Although font size and padding options should be individually available in options per view mode.

**Comment by theboomr** [comment]
As long as there's still a user option to keep the row of buttons always present below posts then I don't mind other aspects of compact mode changing. I personally hate having to tap into a sub-menu or context menu to access commonly used buttons.
