### ISSUE TITLE
Deep-linking on android not working

### ISSUE THREAD

**Issue by DrewBelloc** [liftoff-app/liftoff#410]
### Device info

- OS: Android
- OS version: 11
- Device: Xiaomi Redmi 9
- Liftoff version: v0.10.9

### Describe the bug

When trying to open a url from the browser to liftoff changing "https" to "liftoff" ex:"liftoff://lemmy.world/post/1506733" the browser will just give me a black screen and not even try to open the app, while other apps like rawbt work just fine.

### Steps to reproduce

1. Go to a lemmy post using the web browser.
2. Change the https part of the url for liftoff.

### Relevant logs

There are no logs since the app not even open.

### Expected behavior

The browser should open the post inside of the app.

### Screenshots/Screencasts

![Screenshot_2023-07-15-18-09-47-295_org mozilla fennec_fdroid](https://github.com/liftoff-app/liftoff/assets/139655963/b8bd0e61-2165-4704-ab88-434082b700ac)

![Screenshot_2023-07-15-18-10-33-883_org mozilla fennec_fdroid](https://github.com/liftoff-app/liftoff/assets/139655963/86f2cd3c-f5c9-4e1c-9634-531ef2057530)

### Additional context

Outside of rawbt i don,t really use that feature i other apps, but i was [asked](https://programming.dev/comment/993852) on lemmy to post the issue here.

I've also tried on bromite (a chromium based browser), but it just handles it as a web search.

**Comment by shocklateboy92** [comment]
Looks like that's a chrome thing. When I type [liftoff://lemmy.world/c/liftoff](liftoff://lemmy.world/c/liftoff) in the URL bar, it doesn't work.
But if I click a link with the same URL _in a page_, like on https://lemmy.guide/link?target=!liftoff@lemmy.world it seems to work.
Same with [your link](liftoff://lemmy.world/post/1506733).

**Comment by DrewBelloc** [comment]
I tried again doing the liftoff://url in bromite and i notice that it gives me the option to force to open the url instead of searching, and that way it opens on the app, looks like is a issue with firefox mobile
