### ISSUE TITLE
We need to make swipe to vote/save an option.

### ISSUE THREAD

**Issue by mykdavies** [liftoff-app/liftoff#427]
Lots of user reports about this eg: https://lemmy.world/post/1618669

I think @zachatrocity has this on his radar already, but I don't know if he has anything ready so this is just to get the issue in the log.

### Device info

all

### Describe the bug

Many users are accidentally triggering sideways swipes while scrolling so we need to make it an option. I suggest on by default.

**Comment by Generator** [comment]
Duplicate #407

**Comment by mykdavies** [comment]
Damn, I searched for "swipe" 😄. Closed as duplicate. Thanks!
