### ISSUE TITLE
Use primary color for upvote and downvote

### ISSUE THREAD

**Issue by doug-wade** [liftoff-app/liftoff#440]
### Is your feature request related to a problem? Please describe.

I love the primary color selector! I've chosen a color I really like, and I wish it were applied as the background for the upvote and downvote icon.

![Screenshot_20230722-113239](https://github.com/liftoff-app/liftoff/assets/3477707/5e36b965-6615-476c-88fd-44da7b3843b6)

### Describe the solution you'd like

Use the user-defined primary color for the icon halo on upvotes and downvotes.

### Describe alternatives you've considered

We could have a separate selector just for votes, but that seems a little much

### Additional context

liftoff is great and you're great for making it!

**Comment by shocklateboy92** [comment]
So, we used to have this but ditched it in #374 because the default primary color was awful on most devices.

**Comment by doug-wade** [comment]
@shocklateboy92 great to see we've tried it and gone with what works! Would you like me to close the issue, or is there some third option worth exploring?

**Comment by shocklateboy92** [comment]
Even if we refactor all our action code to make that an option, it would probably not make much sense. 

Let's just close the issue.
