### ISSUE TITLE
Lag on comment-heavy posts

### ISSUE THREAD

**Issue by Slymeball** [liftoff-app/liftoff#51]
### Device info

- OS: Android
- OS version: 11
- Device: Samsung Galaxy A10e
- Liftoff version: 0.9.11

### Describe the bug

When viewing a post with many comments, the app starts to lag considerably.

### Steps to reproduce

1. Go to a post with >~100 comments
2. Scroll down and let comments load
4. Observe how the app lags

### Relevant logs

<details>
  <summary>Logs</summary>
  
 No logs available, the app does not crash.
</details>

### Expected behavior

The app displays comments with no lag.

### Screenshots/Screencasts

My phone doesn't have a built in screen recorder and I'd much rather not install Mobizen or something just for one screen recording. If it's also an issue on desktop, I can open OBS and record it later.

### Additional context

On less commented posts, the app keeps a high framerate.

**Comment by johnc86** [comment]
+1 for this. I think a ListView for commentTree might help?

**Comment by theboomr** [comment]
I also experience this

**Comment by farline99** [comment]
Same here :)

**Comment by jordan1776** [comment]
I notice it even on 9.18 , it is smooth up to 300 comments, around 350 there is slowdown but usable, 500 is the max before it gets really bad. The "3 days" thread is very choppy.

**Comment by zachatrocity** [comment]
Thanks for the update. I'm working on this one as its pretty critical
