### ISSUE TITLE
Hiding read post not working ? 

### ISSUE THREAD

**Issue by seelebrn** [liftoff-app/liftoff#52]
### Device info

- OS: [eg. iOS/Android]
- OS version: [eg. 9]
- Device: [eg. Huawei P20 Lite]
- Liftoff version: [eg. v0. 9.1]

### Describe the bug

As per title. Posts remain on the feed even after upvoting. Show read posts in un checked in the settings. Other apps hide read posts to I suppose it's liftoff's behavior ? 
### Steps to reproduce

1. Go to your feed page 
2. Upvote a post
3. Refrrsh the feed

### Additional context

If no one roses experiences this bug, could be caused by an exceedingly old android version ?

**Comment by zachatrocity** [comment]
this is functioning as intended. after upvoting posts they will not be removed from the feed
