### ISSUE TITLE
Slide or swipe to dismiss/close a post

### ISSUE THREAD

**Issue by Inovvia** [liftoff-app/liftoff#59]
### Is your feature request related to a problem? Please describe.

More of a UX improvement

### Describe the solution you'd like

1. Something similar to infinity/slide swipe to close the post gesture
See below:
https://github.com/r0adkll/Slidr/blob/master/images/slidr_gif.gif

### Describe alternatives you've considered

1. None I have to press the back buton

### Additional context

In slide/infinity I can open a post then use a swiping gesture

If I knew how to do this in flutter I would have created a PR but I only have basic knowledge

**Comment by Inovvia** [comment]
Just noticed that this is actually implemented but you need to use the edge of the screen. Which make this feels inconsistent :(

**Comment by zachatrocity** [comment]
What platform are you on? On Android this is intended and standard functionality

**Comment by Inovvia** [comment]
@zachatrocity I'm using android. I just want to be able using the whole screen instead of the edge only.

**Comment by zachatrocity** [comment]
Gotcha. This was contributed. Should be in the next release

**Comment by mykdavies** [comment]
Looks like this works anywhere in the comments too so as currently implemented would rule out implementing #69.

**Comment by jordan1776** [comment]
> Looks like this works anywhere in the comments too so as currently implemented would rule out implementing #69.

Not exactly, it rules out the apollo style swipe upvotes, but Relay and Sync style swipe interactions (slight pull left for upvote, a little more for downvote, further still for save, even further for reply, with customization in settings for order) are still on the table

**Comment by mykdavies** [comment]
Okay, that's good to know. Interesting how different the details can be between the "must have" features coming from different apps. We might end up having a dropdown to determine which beloved Reddit app the user wants us to be like :-)
