### ISSUE TITLE
This thread was retrieved via lemmy.world. you are not logged in there.

### ISSUE THREAD

**Issue by githubxnoob** [liftoff-app/liftoff#67]
### Device info

- OS: Android
- Liftoff version: v0.9.12

### Describe the bug
to use lemmy i shouldnt have to signup on every instances. i need one account and thats it. since they are all federated i should be able to vote and comment in other instances.
i installed your app and logged in through a custom instance as mine wasnt listed there. 
login was success but then i went to home page but i couldnt interact with any posts on other instances,

i keep getting "This thread was retrieved via lemmy.world. you are not logged in there."

this shouldnt be a thing on a federated lemmy.

i was able to comment and upvote on browser with other instances. so its not a federation issue.

also the "everything feed" on setting is also disabled.

app should be easy and automatically send my comment and upvotes via my instance to other instances.

### Steps to reproduce

1. install liftoff and signin through custom instance.
2. after login go to front page.
3. you can upvote comment on your local instance
4. if you try to upvote comment on any other instance post or comment you get the error.

### Relevant logs
it says no logs.

### Expected behavior

once i logged in through any one instances. i should be able to upvote,comment on any instances.

**Comment by mykdavies** [comment]
Hi, what feed are you viewing? If you've logged in to say mylemmy.instance, and you're viewing a "....@mylemmy.instance" feed, everything should work as expected.

 If you're using the Everything feed, or "...@lemmy.world" etc, you will be seeing feeds from the other instances, which would require you to logon to interact with comments on their instance.

Let me know if this helps.

**Comment by EoN-kCw1u5Sh1Ws** [comment]
I'm getting the same here while logged into an instance that isn't lemmy.world, lemmy.ml or beehaw.org.

If I select All@my.instance I'm shown the all feed from my instance. This includes communities I'm not subscribed to.

I can't at the moment, but I'll try to replicate it.

**Comment by zachatrocity** [comment]
This has been fixed (or at least made more clear) and the defaults have been removed in #146
