### ISSUE TITLE
Wrong community reported for account posts

### ISSUE THREAD

**Issue by josevh** [liftoff-app/liftoff#81]
### Device info

- OS: Android
- OS version: 13
- Device: Samsung Galaxy S22
- Liftoff version: v0.9.12

### Describe the bug

When viewing the logged in account's posts, the cards incorrectly display the community as if it were from the instance the account is from.

### Steps to reproduce

1. Login to a Lemmy account subscribed to communities not of that instance. Ensure the account has made a post to that community.
2. Navigate to the profile view and click the Posts tab button.
3. Scroll to a post from made in a community not of the instance the account is from.
4. See error.
5. Open the post.
6. See error there too.

### Relevant logs
N/A

### Expected behavior

All account posts should accurately display the community where they were posted.

### Screenshots/Screencasts

In the screenshots below, there is no `!citiesskylines@programming.dev`, that community is at `lemmy.ml`.

![Screenshot_20230625_083245](https://github.com/liftoff-app/liftoff/assets/8278253/a4d61340-95f6-48a7-b620-0059991f4eff)

![Screenshot_20230625_083306](https://github.com/liftoff-app/liftoff/assets/8278253/89a1b1e9-2ded-49a9-84ba-ab370059791e)

![Screenshot_20230625_083840](https://github.com/liftoff-app/liftoff/assets/8278253/099f17e3-ef0f-486b-adc9-0a389c40b38e)

### Additional context

N/A

**Comment by zachatrocity** [comment]
closing in favor of #142 which has a PR submission
