### ISSUE TITLE
cant use my instance

### ISSUE THREAD

**Issue by Tealk** [liftoff-app/liftoff#89]
### Device info

- OS: Android
- OS version: 13
- Device: Pixel 6
- Liftoff version: 0.9.12

### Describe the bug

I can't setup my Instance `lemmy.rollenspiel.monster`. I get the message `Instance not found`

### Steps to reproduce

1. Open App
2. Click on Accounts
3. Click on "Add account"
4. Click on Sandwitch menu
5. Click "Add instance"
6. Add URL

**Comment by swmarks** [comment]
I'm able to add your instance on my phone. Did you change anything and/or are you still having issues?

**Comment by Tealk** [comment]
No I didn't change anything, but now it works for me too. Crazy

**Comment by Tealk** [comment]
> Oh yes, I have turned off the currently not working captcha and enabled manual registration

But that can't have anything to do with finding the instance?
