### ISSUE TITLE
Swap press and hold functionality

### ISSUE THREAD

**Issue by Puripu** [liftoff-app/liftoff#90]
Currently you have to long press to collapse a comment. Single press shows up vote etc 

It would be really nice to have a toggle to swap this behaviour. (most reddit clients used to have this option.)

**Comment by waldyrious** [comment]
> It would be really nice to have a toggle to swap this behaviour.

For the record, I have opened a separate issue asking to make the behavior configurable (as opposed to changing the default): #267
